steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'us-central1-docker.pkg.dev/a-counting-sign-language/pjg-mediapipe-demo/pjg-mediapipe-demo', '.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/a-counting-sign-language/pjg-mediapipe-demo/pjg-mediapipe-demo']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'pjg-mediapipe-demo'
      - '--image'
      - 'us-central1-docker.pkg.dev/a-counting-sign-language/pjg-mediapipe-demo/pjg-mediapipe-demo'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
images:
  - 'us-central1-docker.pkg.dev/a-counting-sign-language/pjg-mediapipe-demo/pjg-mediapipe-demo'